import React from 'react';
import { ArrowLeft, Bookmark, CalendarDays, CheckCircle2, ExternalLink, MapPin } from 'lucide-react';
import { fetchOpportunityBySlug, fetchSavedOpportunityIds, toggleSavedOpportunity, type Opportunity } from '../lib/opportunities';
import { isSafeHttpsUrl } from '../lib/opportunity-domain.mjs';

export const OpportunityDetailPage: React.FC<{ slug: string; userId: string | null; onBack: () => void; onRequireLogin: () => void }> = ({ slug, userId, onBack, onRequireLogin }) => {
 const [item,setItem]=React.useState<Opportunity|null>(null); const [saved,setSaved]=React.useState(false); const [state,setState]=React.useState<'loading'|'ready'|'missing'>('loading');
 React.useEffect(()=>{ let off=false; Promise.all([fetchOpportunityBySlug(slug),userId?fetchSavedOpportunityIds(userId):Promise.resolve([])]).then(([row,ids])=>{if(!off){setItem(row);setSaved(Boolean(row&&ids.includes(row.id)));setState(row?'ready':'missing');}}).catch(()=>{if(!off)setState('missing');}); return()=>{off=true};},[slug,userId]);
 React.useEffect(()=>{if(item){document.title=`${item.title} | StajımVar`; const d=document.querySelector('meta[name="description"]')||Object.assign(document.createElement('meta'),{name:'description'});d.setAttribute('content',item.shortDescription);document.head.appendChild(d);}},[item]);
 if(state==='loading')return <main className="max-w-4xl mx-auto p-6"><div className="h-80 rounded-3xl bg-gray-100 animate-pulse"/></main>; if(!item)return <main className="max-w-3xl mx-auto p-6 text-center"><h1 className="text-xl font-bold">Bu fırsat bulunamadı veya artık yayında değil</h1><button onClick={onBack} className="mt-4 text-blue-700 font-bold">Fırsatlara dön</button></main>;
 const toggle=async()=>{if(!userId)return onRequireLogin();await toggleSavedOpportunity(userId,item.id,saved);setSaved(!saved)}; const link=isSafeHttpsUrl(item.applicationUrl||'')?item.applicationUrl:isSafeHttpsUrl(item.sourceUrl)?item.sourceUrl:null;
 return <main className="max-w-4xl mx-auto w-full px-4 sm:px-6 py-7 pb-24 space-y-6"><button onClick={onBack} className="inline-flex gap-1 items-center text-sm font-bold text-gray-600 hover:text-gray-950"><ArrowLeft className="w-4 h-4"/>Fırsatlara dön</button><article className="rounded-3xl border border-gray-200 bg-white p-6 sm:p-8 shadow-sm"><div className="flex flex-col sm:flex-row sm:justify-between gap-5"><div><span className="text-xs font-bold text-blue-700 uppercase">{item.opportunityType}</span><h1 className="mt-2 text-2xl sm:text-3xl font-extrabold text-gray-950">{item.title}</h1><p className="mt-2 text-gray-600 font-semibold">{item.organizationName}</p></div><button aria-label="Fırsatı kaydet" onClick={toggle} className={`self-start rounded-xl px-3 py-2 text-sm font-bold inline-flex gap-2 ${saved?'bg-blue-50 text-blue-700':'bg-gray-100 text-gray-700'}`}><Bookmark className="w-4 h-4" fill={saved?'currentColor':'none'}/>{saved?'Kaydedildi':'Kaydet'}</button></div><p className="mt-6 text-gray-700 leading-relaxed whitespace-pre-line">{item.description||item.shortDescription}</p><div className="mt-7 grid sm:grid-cols-2 gap-4 text-sm"><Info title="Kimler başvurabilir?" body={item.eligibility||item.educationLevels.join(', ')||'Resmî kaynakta belirtilir.'}/><Info title="Destek veya ödül" body={item.amountText||item.supportType||'Belirtilmemiş'}/><Info title="Başvuru tarihleri" body={`${item.applicationStartAt?new Intl.DateTimeFormat('tr-TR',{dateStyle:'long'}).format(new Date(item.applicationStartAt)):'Başlangıç belirtilmemiş'} — ${item.applicationDeadline?new Intl.DateTimeFormat('tr-TR',{dateStyle:'long'}).format(new Date(item.applicationDeadline)):'Son tarih belirtilmemiş'}`}/><Info title="Şehir / ülke" body={[...item.cities,...item.countries].join(', ')||'Belirtilmemiş'}/><Info title="Gerekli belgeler" body={item.requiredDocuments.join(', ')||'Resmî kaynakta belirtilir.'}/><Info title="Son kontrol" body={item.lastCheckedAt?new Intl.DateTimeFormat('tr-TR',{dateStyle:'long'}).format(new Date(item.lastCheckedAt)):'Belirtilmemiş'}/></div><div className="mt-8 flex flex-wrap gap-3"><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-gray-300 px-4 py-2.5 text-sm font-bold text-gray-800"><CheckCircle2 className="w-4 h-4 text-emerald-600"/>Resmî kaynak</a>{link&&<a href={link} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Resmî sayfada başvur <ExternalLink className="w-4 h-4"/></a>}</div></article></main>;
};
const Info:React.FC<{title:string;body:string}>=({title,body})=><section className="rounded-2xl bg-gray-50 p-4"><h2 className="font-bold text-gray-900">{title}</h2><p className="mt-1 text-gray-600 leading-relaxed">{body}</p></section>;
