create type public.opportunity_source_type as enum ('government','university','municipality','foundation','association','company','international_official','discovery_only');
create type public.opportunity_source_trust as enum ('official','trusted','discovery','blocked');
create type public.opportunity_import_status as enum ('discovered','fetching','needs_review','approved','imported','duplicate','rejected','failed','stale');

create table public.opportunity_sources (
 id uuid primary key default gen_random_uuid(), name text not null, base_url text not null unique, source_type public.opportunity_source_type not null, trust_level public.opportunity_source_trust not null, discovery_method text not null, parser_type text not null, enabled boolean not null default true, robots_allowed boolean not null default false, last_checked_at timestamptz, last_success_at timestamptz, consecutive_failures integer not null default 0 check(consecutive_failures >= 0), check_interval_minutes integer not null default 1440 check(check_interval_minutes between 15 and 10080), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(base_url ~* '^https://' and base_url !~* '^https://(localhost|127\\.|0\\.|10\\.|192\\.168\\.|169\\.254\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.|\\[::1\\]|\\[(fc|fd|fe80))')
);
create table public.opportunity_import_candidates (
 id uuid primary key default gen_random_uuid(), discovered_url text not null, canonical_url text not null unique, source_id uuid references public.opportunity_sources(id) on delete restrict, detected_title text, detected_organization text, detected_academic_year text check(detected_academic_year ~ '^20[0-9]{2}-20[0-9]{2}$'), raw_fingerprint text not null unique, status public.opportunity_import_status not null default 'discovered', confidence_score integer not null default 0 check(confidence_score between 0 and 100), rejection_reason text, linked_opportunity_id uuid references public.opportunities(id) on delete set null, first_seen_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, retry_after timestamptz, attempt_count integer not null default 0 check(attempt_count between 0 and 8), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(canonical_url ~* '^https://')
);
alter table public.opportunities add column academic_year text check(academic_year is null or academic_year ~ '^20[0-9]{2}-20[0-9]{2}$'), add column source_id uuid references public.opportunity_sources(id) on delete restrict, add column canonical_source_url text, add column source_fingerprint text, add column import_candidate_id uuid references public.opportunity_import_candidates(id) on delete set null, add column import_method text, add column confidence_score integer check(confidence_score between 0 and 100), add column auto_publish_eligible boolean not null default false, add column first_seen_at timestamptz, add column last_seen_at timestamptz, add column archived_at timestamptz, add column purge_after timestamptz, add column content_hash text;
create unique index opportunities_canonical_source_url_key on public.opportunities(canonical_source_url) where canonical_source_url is not null;
create index opportunity_import_candidates_status_retry_idx on public.opportunity_import_candidates(status,retry_after);
alter table public.opportunity_sources enable row level security; alter table public.opportunity_import_candidates enable row level security;
create policy "yonetici kaynaklari yonetir" on public.opportunity_sources for all using(public.is_admin()) with check(public.is_admin());
create policy "yonetici import kuyrugunu yonetir" on public.opportunity_import_candidates for all using(public.is_admin()) with check(public.is_admin());
create trigger t8_opportunity_sources_updated before update on public.opportunity_sources for each row execute function public.touch_updated_at();
create trigger t9_opportunity_import_candidates_updated before update on public.opportunity_import_candidates for each row execute function public.touch_updated_at();
